// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLcx_0WUKfh17dBBE5ZcWeuThBYHNvveo',
    appId: '1:358528335538:web:e2fe0fab435ee3bfc413ab',
    messagingSenderId: '358528335538',
    projectId: 'loginapp-606ad',
    authDomain: 'loginapp-606ad.firebaseapp.com',
    storageBucket: 'loginapp-606ad.firebasestorage.app',
    measurementId: 'G-RPQ8JW84Q6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnI2yIHS1sco2-3-6mrEYAnvyrkT35Yq8',
    appId: '1:358528335538:android:cfc2f27637adfba6c413ab',
    messagingSenderId: '358528335538',
    projectId: 'loginapp-606ad',
    storageBucket: 'loginapp-606ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSk_xyaZNfMdw1iZrw888ScBG60f0whD8',
    appId: '1:358528335538:ios:84c0dee9fb41a53cc413ab',
    messagingSenderId: '358528335538',
    projectId: 'loginapp-606ad',
    storageBucket: 'loginapp-606ad.firebasestorage.app',
    iosBundleId: 'com.example.loginSignupPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSk_xyaZNfMdw1iZrw888ScBG60f0whD8',
    appId: '1:358528335538:ios:84c0dee9fb41a53cc413ab',
    messagingSenderId: '358528335538',
    projectId: 'loginapp-606ad',
    storageBucket: 'loginapp-606ad.firebasestorage.app',
    iosBundleId: 'com.example.loginSignupPage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLcx_0WUKfh17dBBE5ZcWeuThBYHNvveo',
    appId: '1:358528335538:web:d6b762f78e089d8ac413ab',
    messagingSenderId: '358528335538',
    projectId: 'loginapp-606ad',
    authDomain: 'loginapp-606ad.firebaseapp.com',
    storageBucket: 'loginapp-606ad.firebasestorage.app',
    measurementId: 'G-QEHQTR8F7N',
  );

}